<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FilmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('films')->insert([
            [
                'status' => true,
                'name_ua' => 'Матриця',
                'name_en' => 'The Matrix',
                'description_ua' => 'Опис фільму',
                'description_en' => 'Thomas Anderson leads a double life. By day, he works as a computer software technician, and by night, he becomes a brilliant hacker known as Neo. One night, Neo meets Trinity, a mysterious woman who leads him to Morpheus...',
                'poster' => 'The-Matrix.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
                'year' => '1999',
                'start_date' => '2025-11-04 18:30:00',
                'end_date' => '2025-11-08 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Початок',
                'name_en' => 'Inception',
                'description_ua' => 'Опис фільму',
                'description_en' => 'Dom Cobb is a thief with the rare ability to enter people’s dreams and steal their secrets. His skill made him a coveted player in corporate espionage, but it also cost him everything he loved.',
                'poster' => 'Inception.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'year' => '2010',
                'start_date' => '2025-11-05 18:30:00',
                'end_date' => '2025-11-09 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Месники: Завершення',
                'name_en' => 'Avengers: Endgame',
                'description_ua' => 'Опис фільму',
                'description_en' => 'After the devastating events of Infinity War, the universe is in ruins. The Avengers assemble once more to reverse Thanos’s actions and restore balance to the universe.',
                'poster' => 'Avengers-Endgame.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
                'year' => '2019',
                'start_date' => '2025-11-06 18:30:00',
                'end_date' => '2025-11-10 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Темний лицар',
                'name_en' => 'The Dark Knight',
                'description_ua' => 'Опис фільму',
                'description_en' => 'Batman faces his greatest psychological and physical tests yet when the Joker, a sadistic criminal mastermind, unleashes chaos upon Gotham City.',
                'poster' => 'The-Dark-Knight.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'year' => '2008',
                'start_date' => '2025-11-07 18:30:00',
                'end_date' => '2025-11-11 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Бійцівський клуб',
                'name_en' => 'Fight Club',
                'description_ua' => 'Опис фільму',
                'description_en' => 'A depressed man suffering from insomnia meets a strange soap salesman named Tyler Durden, and soon finds himself living in a rundown house and forming an underground fight club.',
                'poster' => 'Fight-Club.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=SUXWAEX2jlg',
                'year' => '1999',
                'start_date' => '2025-11-08 18:30:00',
                'end_date' => '2025-11-12 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Форест Гамп',
                'name_en' => 'Forrest Gump',
                'description_ua' => 'Опис фільму',
                'description_en' => 'Forrest Gump, a man with a low IQ but pure intentions, unwittingly influences several historical events in the 20th century while pursuing his one true love, Jenny.',
                'poster' => 'Forrest-Gump.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=bLvqoHBptjg',
                'year' => '1994',
                'start_date' => '2025-11-09 18:30:00',
                'end_date' => '2025-11-13 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Втеча з Шоушенка',
                'name_en' => 'The Shawshank Redemption',
                'description_ua' => 'Опис фільму',
                'description_en' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'poster' => 'The-Shawshank-Redemption.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=NmzuHjWmXOc',
                'year' => '1994',
                'start_date' => '2025-11-10 18:30:00',
                'end_date' => '2025-11-14 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Паразити',
                'name_en' => 'Parasite',
                'description_ua' => 'Опис фільму',
                'description_en' => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
                'poster' => 'Parasite.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=5xH0HfJHsaY',
                'year' => '2019',
                'start_date' => '2025-11-11 18:30:00',
                'end_date' => '2025-11-15 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Інтерстеллар',
                'name_en' => 'Interstellar',
                'description_ua' => 'Опис фільму',
                'description_en' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival.',
                'poster' => 'Interstellar.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
                'year' => '2014',
                'start_date' => '2025-11-12 18:30:00',
                'end_date' => '2025-11-16 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Джокер',
                'name_en' => 'Joker',
                'description_ua' => 'Опис фільму',
                'description_en' => 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He embarks on a downward spiral of revolution and crime.',
                'poster' => 'Joker.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
                'year' => '2019',
                'start_date' => '2025-11-13 18:30:00',
                'end_date' => '2025-11-17 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Білий лотос',
                'name_en' => 'The White Lotus',
                'description_ua' => 'Опис фільму',
                'description_en' => 'A social satire set in an exclusive Hawaiian resort, where guests and staff become entangled in complex moral conflicts over the course of a week.',
                'poster' => 'The-White-Lotus.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=2e6blKzdqQI',
                'year' => '2021',
                'start_date' => '2025-11-14 18:30:00',
                'end_date' => '2025-11-18 18:30:00',
            ],
            [
                'status' => true,
                'name_ua' => 'Титанік',
                'name_en' => 'Titanic',
                'description_ua' => 'Опис фільму',
                'description_en' => 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
                'poster' => 'Titanic.jpg',
                'screenshots' => true,
                'trailer_url' => 'https://www.youtube.com/watch?v=2e-eXJ6HgkQ',
                'year' => '1997',
                'start_date' => '2025-11-15 18:30:00',
                'end_date' => '2025-11-19 18:30:00',
            ],
        ]);

    }
}
